"""
Django settings for api_server project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json_log_formatter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#os.makedirs(BASE_DIR / "logs", exist_ok=True) # 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "fallback-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # []だと外部からのリクエストをすべて無視


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapi",
    "rest_framework",
    "django_filters", # Enables REST API endpoints to GET, UPDATE, and DELETE items by product name
]

# HTTPリクエストがDjangoアプリに入ってきたときの処理の流れ(パイプライン)を定義するための項目。
# ここの後URLルーティングにしたがい適切なviews.pyに渡される。だから最後にLoggingMiddlewareを書く。
# Djangoのミドルウェアは、リクエストがViews.pyに到達する前と、レスポンスがブラウザに返される前に
# 処理を挟み込むための「層」のようなもの。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'myapi.middleware.LoggingMiddleware', # Enables logging for Django and myapi/middleware.py
]

ROOT_URLCONF = "api_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
    # DEFAULT_RENDERER_CLASSES:APIのレスポンスをどのような形式で表示するかを制御    
        'rest_framework.renderers.JSONRenderer',
        # JSONRenderer:Sets the API to render responses in JSON format
        'rest_framework.renderers.BrowsableAPIRenderer',
        # BrowsableAPIRenderer:Enables API testing directly from the browser using the browsable API
    ],
    'DEFAULT_FILTER_BACKENDS': [
    # DEFAULT_FILTER_BACKENDS:Defines the default filter backends for the API
        'django_filters.rest_framework.DjangoFilterBackend',
        # views.pyにもDjangoFilterBackendの設定必要
    ],

}

WSGI_APPLICATION = "api_server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # Formatters(フォーマッター):ログをどのような形式で出力するか
    'formatters': {
        'json': {
            '()': json_log_formatter.JSONFormatter,
        },
    },
    # Handlers(ハンドラー):ログをどこに出力するか
    'handlers': {
        'console': {
            'level': 'INFO', # INFOレベル以上のログをコンソールに出力
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'file': {
            'level': 'DEBUG', # DEBUGレベル以上のログをファイルに出力
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'api_server.log'),
            'formatter': 'json',
        },
    },
    #Loggers(ロガー):アプリケーションコードからログを発行するための窓口
    'loggers': {
        'django': {
            #'handlers': ['console', 'file'],
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'myapi.middleware': {
            #'handlers': ['console', 'file'],
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
